"""NanoID primary-key base model + the shared id generator.

Foundation for CC-77 (epic) — every model's integer primary key is being
replaced by an opaque 10-char NanoID PK (a TRUE primary-key swap, not an
additive ``public_id`` column). This module is the reusable base that the
JobPost slice (#57) and the remaining-models rollout (#79) copy: subclass
``NanoIDModel`` instead of ``models.Model`` and the model gets a NanoID
string PK.

## The id format — frontend + extension MUST validate against this

- Library: ``nanoid`` (PyPI).
- Alphabet: ``NANOID_ALPHABET`` — the 62 URL-safe **alphanumerics**
  ``0-9 A-Z a-z``. We deliberately drop nanoid's default ``-`` and ``_``
  so an id is clean in URLs, ActivityPub object ids and route segments
  with zero escaping, and validates with a trivial character class.
- Size: ``NANOID_SIZE`` = 10 characters.
- Validation regex (anchored): ``NANOID_REGEX`` = ``^[0-9A-Za-z]{10}$``
  (compiled form exported as ``NANOID_RE``).

10 chars over a 62-symbol alphabet is ``62**10`` ≈ 8.4e17 keyspace — at
this app's scale (a few thousand rows per model) the collision
probability is negligible. The PK unique index is the backstop: on the
astronomically rare clash an ``IntegrityError`` is raised at INSERT and
the caller retries (the field default mints a fresh id each attempt).

## Adopting this on an EXISTING table

Swapping a populated integer PK to a NanoID PK with dependent FKs is a
destructive, hand-crafted migration that is NOT auto-generated by
``makemigrations``. Use ``0114_skill_nanoid_pk_swap`` as the template:
add staging columns -> backfill -> dynamic FK/constraint drop -> promote
-> recreate constraints, wrapped in ``SeparateDatabaseAndState`` so
Django's migration state stays in sync with the hand-written SQL.
"""

from __future__ import annotations

import re

from django.db import models
from nanoid import generate

#: URL-safe alphanumeric alphabet (62 symbols, no ``-``/``_``).
NANOID_ALPHABET = (
    "0123456789"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
)
#: Length of every generated id, in characters.
NANOID_SIZE = 10
#: Anchored validation pattern for a well-formed id (mirror this in the
#: frontend + the ccsender extension).
NANOID_REGEX = r"^[0-9A-Za-z]{10}$"
#: Pre-compiled form of :data:`NANOID_REGEX`.
NANOID_RE = re.compile(NANOID_REGEX)


def generate_nanoid() -> str:
    """Return a fresh 10-char URL-safe NanoID over :data:`NANOID_ALPHABET`.

    Defined at module level (not a lambda or local closure) so Django
    migrations can serialize it as
    ``job_hunting.models.nanoid_pk.generate_nanoid`` for the ``id`` field
    default.
    """
    return generate(NANOID_ALPHABET, NANOID_SIZE)


class NanoIDModel(models.Model):
    """Abstract base giving a model an opaque 10-char NanoID string PK.

    Swap ``models.Model`` -> ``NanoIDModel`` on a model and its ``id``
    becomes a client-unguessable string primary key. Composes with
    ``GetMixin`` exactly like ``models.Model`` did, e.g.::

        class Skill(GetMixin, NanoIDModel):
            ...
    """

    id = models.CharField(
        primary_key=True,
        max_length=NANOID_SIZE,
        default=generate_nanoid,
        editable=False,
    )

    class Meta:
        abstract = True
