"""CC-221 — the migration history must fully describe the models.

Three tests, and it takes all three to be worth anything:

``test_makemigrations_reports_no_changes`` is the state half. Uncaptured drift
is not merely untidy — it silently attaches itself to the *next* migration
somebody writes, so every author has to notice it and hand-strip it (CC-204
and CC-213 both did). Failing here turns that into a red build with a diff
attached instead of a papercut nobody logs.

``test_the_gate_answers_rename_questions_itself`` guards the gate itself.
``makemigrations`` builds an ``InteractiveMigrationQuestioner`` unless it is
told otherwise, and ``ask_rename``/``ask_rename_model`` — unlike the
not-null questions — have no ``if not self.dry_run`` guard, so a field or
model rename walks straight into ``input()``. The prompt goes to the
command's ``stdout``, which here is a captured ``StringIO``, so under CI the
gate would die with a bare ``EOFError`` (not ``SystemExit``, so none of the
guidance below ever prints) and under a TTY it would hang with nothing on
screen. A rename is the most common drift shape there is, so the gate has to
answer that question without a terminal.

``test_indexed_columns_have_a_backing_index`` is the schema half.
``makemigrations`` compares migration *state* to the model classes and never
looks at a database, so raw SQL can delete or rename an index and state will
never notice. Two flavours of that are checked, and the split is deliberate:

* Every ``Meta.indexes`` name must exist verbatim. These are the names
  migration state manipulates by name (``RenameIndex``, ``RemoveIndex``), so
  a mismatch is a live crash — 0124's PK swap recreated the ``company_id``
  indexes under its own names and the autogenerated ``RenameIndex`` blew up
  with ``relation ... does not exist`` on the first real ``migrate``.

* Every ``db_index`` column must have *some* btree leading on it. Names are
  deliberately not asserted here, because they are already wrong nearly
  everywhere: the nanoid PK swaps (0119–0124) rebuilt ~45 FK columns in raw
  SQL and recreated one hand-named ``<table>_<column>_idx`` apiece, so the
  Django-hashed ``<table>_<column>_<hash>`` index and its ``_like`` sibling
  are absent across most of the schema. Repairing that is its own ticket.
  What this assertion does buy is the one failure mode that actually loses
  data-path performance: after 0138, ``company_alias.company_id`` and
  ``federation_followers.company_id`` are down to a *single* index that now
  bears a ``Meta.indexes`` name, so a future ``RemoveIndex`` on it would
  leave the FK with no index at all. That now fails the build.
"""

import io
from unittest import mock

from django.apps import apps
from django.core.management import call_command
from django.db import connection, models
from django.db.migrations.autodetector import MigrationAutodetector
from django.db.migrations.state import ModelState
from django.test import TestCase

# Indexes whose leading column we can attribute to a model field.
LEADING_INDEX_COLUMNS = """
SELECT c.relname, a.attname
FROM pg_index x
JOIN pg_class c ON c.oid = x.indrelid
JOIN pg_class i ON i.oid = x.indexrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = x.indkey[0]
WHERE n.nspname = current_schema()
"""


def run_migration_check(out):
    """Invoke the gate. ``interactive=False`` is load-bearing — see module docstring."""
    call_command(
        "makemigrations",
        "job_hunting",
        check_changes=True,
        dry_run=True,
        interactive=False,
        verbosity=1,
        stdout=out,
        stderr=out,
    )


class MigrationDriftTests(TestCase):
    def test_makemigrations_reports_no_changes(self):
        """``makemigrations --check --dry-run`` must exit clean."""
        out = io.StringIO()
        try:
            run_migration_check(out)
        except SystemExit:
            self.fail(
                "Model definitions have drifted from the migration history. "
                "Run `python manage.py makemigrations job_hunting` and commit "
                "the result as its own migration — do not fold it into an "
                "unrelated one. Detected changes:\n\n" + out.getvalue()
            )

    def test_the_gate_answers_rename_questions_itself(self):
        """A rename must not send the gate to ``input()``."""
        answers = []
        detect_renames = MigrationAutodetector.create_renamed_fields

        def ask_a_rename_first(detector):
            answers.append(
                detector.questioner.ask_rename(
                    "Company", "name", "title", models.CharField()
                )
            )
            answers.append(
                detector.questioner.ask_rename_model(
                    ModelState("job_hunting", "Company", []),
                    ModelState("job_hunting", "Employer", []),
                )
            )
            return detect_renames(detector)

        out = io.StringIO()
        with (
            mock.patch.object(
                MigrationAutodetector, "create_renamed_fields", ask_a_rename_first
            ),
            mock.patch(
                "builtins.input",
                side_effect=AssertionError(
                    "the drift gate prompted for input — it will EOFError under "
                    "CI and hang under a TTY, and the prompt is invisible either "
                    "way because it is written to the captured stdout"
                ),
            ),
        ):
            run_migration_check(out)

        self.assertEqual(
            answers,
            [False, False],
            "the gate's questioner must answer rename questions with the "
            "non-interactive default, so a rename shows up as a plain "
            "remove+add in the failure diff",
        )

    def test_declared_meta_indexes_exist_in_the_database(self):
        """Every ``Meta.indexes`` name must name a real index."""
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT indexname FROM pg_indexes "
                "WHERE schemaname = current_schema()"
            )
            present = {row[0] for row in cursor.fetchall()}

        missing = []
        for model in apps.get_app_config("job_hunting").get_models():
            for index in model._meta.indexes:
                if index.name not in present:
                    missing.append(f"{model.__name__}.Meta: {index.name}")

        self.assertEqual(
            missing,
            [],
            "Indexes declared on the models are absent from the database — "
            "migration state and schema have diverged, most likely because a "
            "raw-SQL migration recreated them under a different name:\n"
            + "\n".join(missing),
        )

    def test_indexed_columns_have_a_backing_index(self):
        """Every ``db_index`` column must have *some* btree leading on it."""
        with connection.cursor() as cursor:
            cursor.execute(LEADING_INDEX_COLUMNS)
            indexed_columns = {(row[0], row[1]) for row in cursor.fetchall()}

        unbacked = []
        for model in apps.get_app_config("job_hunting").get_models():
            table = model._meta.db_table
            for field in model._meta.local_fields:
                if field.primary_key or not field.db_index:
                    continue
                if (table, field.column) not in indexed_columns:
                    unbacked.append(
                        f"{model.__name__}.{field.name} "
                        f"-> {table}.{field.column}"
                    )

        self.assertEqual(
            unbacked,
            [],
            "Columns the models declare as indexed have no index at all in the "
            "database. Dropping an index by name is only safe when another one "
            "still leads on the column:\n" + "\n".join(unbacked),
        )
