"""CC-221 — the migration history must fully describe the models.

Two halves of one invariant, and it takes both to be safe:

``test_makemigrations_reports_no_changes`` is the state half. Uncaptured drift
is not merely untidy — it silently attaches itself to the *next* migration
somebody writes, so every author has to notice it and hand-strip it (CC-204
and CC-213 both did). Failing here turns that into a red build with a diff
attached instead of a papercut nobody logs.

``test_declared_meta_indexes_exist_in_the_database`` is the schema half, and
it is the one that would have caught the bug CC-221 tripped over. Migration
0124's raw-SQL PK swap recreated the ``company_id`` indexes under new names.
``makemigrations`` cannot see that — it only ever compares migration *state*
to the model classes, never to a real database — so state went on believing
in ``company_ali_company_idx``/``fed_fwr_company_idx`` long after the
database had dropped them, and the autogenerated ``RenameIndex`` for those
two blew up with ``relation ... does not exist`` on the first real ``migrate``.
Asserting declared index names against ``pg_indexes`` closes that blind spot.
"""

import io

from django.apps import apps
from django.core.management import call_command
from django.db import connection
from django.test import TestCase


class MigrationDriftTests(TestCase):
    def test_makemigrations_reports_no_changes(self):
        """``makemigrations --check --dry-run`` must exit clean."""
        out = io.StringIO()
        try:
            call_command(
                "makemigrations",
                check_changes=True,
                dry_run=True,
                verbosity=1,
                stdout=out,
                stderr=out,
            )
        except SystemExit:
            self.fail(
                "Model definitions have drifted from the migration history. "
                "Run `python manage.py makemigrations` and commit the result "
                "as its own migration — do not fold it into an unrelated "
                "one. Detected changes:\n\n" + out.getvalue()
            )

    def test_declared_meta_indexes_exist_in_the_database(self):
        """Every ``Meta.indexes`` name must name a real index."""
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT indexname FROM pg_indexes "
                "WHERE schemaname = current_schema()"
            )
            present = {row[0] for row in cursor.fetchall()}

        missing = []
        for model in apps.get_app_config("job_hunting").get_models():
            for index in model._meta.indexes:
                if index.name not in present:
                    missing.append(f"{model.__name__}.Meta: {index.name}")

        self.assertEqual(
            missing,
            [],
            "Indexes declared on the models are absent from the database — "
            "migration state and schema have diverged, most likely because a "
            "raw-SQL migration recreated them under a different name:\n"
            + "\n".join(missing),
        )
