# Generated by Django 4.0.10 on 2026-03-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0001_status_django_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
    ]
