# Generated by Django 4.0.10 on 2026-03-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0002_skill_django_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'description',
            },
        ),
    ]
