# Generated by Django 4.0.10 on 2026-03-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0004_certification_django_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('minor', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'education',
            },
        ),
    ]
