# Generated by Django 4.0.10 on 2026-03-14 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0019_wave2_django_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, null=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_summaries', to='job_hunting.resume')),
                ('summary', models.ForeignKey(db_column='summary_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_summaries', to='job_hunting.summary')),
            ],
            options={
                'db_table': 'resume_summaries',
            },
        ),
        migrations.CreateModel(
            name='ResumeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_projects', to='job_hunting.project')),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_projects', to='job_hunting.resume')),
            ],
            options={
                'db_table': 'resume_project',
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('experience', models.ForeignKey(db_column='experience_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_experiences', to='job_hunting.experience')),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_experiences', to='job_hunting.resume')),
            ],
            options={
                'db_table': 'resume_experience',
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('education', models.ForeignKey(db_column='education_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_educations', to='job_hunting.education')),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_educations', to='job_hunting.resume')),
            ],
            options={
                'db_table': 'resume_education',
            },
        ),
        migrations.CreateModel(
            name='ResumeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('certification', models.ForeignKey(db_column='certification_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_certifications', to='job_hunting.certification')),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_certifications', to='job_hunting.resume')),
            ],
            options={
                'db_table': 'resume_certification',
            },
        ),
        migrations.CreateModel(
            name='ProjectDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.ForeignKey(db_column='description_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_descriptions', to='job_hunting.description')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_descriptions', to='job_hunting.project')),
            ],
            options={
                'db_table': 'project_description',
            },
        ),
        migrations.CreateModel(
            name='JobApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='application_statuses', to='job_hunting.application')),
                ('status', models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_application_statuses', to='job_hunting.status')),
            ],
            options={
                'db_table': 'job_application_status',
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_skills', to='job_hunting.resume')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_skills', to='job_hunting.skill')),
            ],
            options={
                'db_table': 'resume_skill',
                'unique_together': {('resume', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='ExperienceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('description', models.ForeignKey(db_column='description_id', on_delete=django.db.models.deletion.CASCADE, related_name='experience_descriptions', to='job_hunting.description')),
                ('experience', models.ForeignKey(db_column='experience_id', on_delete=django.db.models.deletion.CASCADE, related_name='experience_descriptions', to='job_hunting.experience')),
            ],
            options={
                'db_table': 'experience_description',
                'unique_together': {('experience', 'description')},
            },
        ),
    ]
