# Generated by Django 4.0.10 on 2026-03-21 23:17

from django.db import migrations
import job_hunting.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0021_rename_application_to_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='links',
            field=job_hunting.models.profile.SafeJSONField(blank=True, default=dict, null=True),
        ),
    ]
