# Generated by Django 4.0.10 on 2026-03-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0022_alter_profile_links'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobapplication',
            table='job_application',
        ),
    ]
