# Generated by Django 4.0.10 on 2026-03-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0023_rename_application_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
