# Generated by Django 6.0.3 on 2026-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0028_scrape_state_to_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplicationstatus",
            name="logged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
