# Generated by Django 6.0.3 on 2026-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0029_add_logged_at_to_job_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
