# Generated by Django 5.2.12 on 2026-04-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0031_question_job_post_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
