# Generated by Django 5.2.12 on 2026-04-09 22:55

import job_hunting.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0032_profile_is_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'waitlist',
                'ordering': ['-created_at'],
            },
            bases=(job_hunting.models.base.GetMixin, models.Model),
        ),
    ]
