# Generated by Django 6.0.3 on 2026-04-13 15:19

import django.db.models.deletion
import job_hunting.models.base
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0034_add_created_by_to_scrape"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("trigger", models.CharField(max_length=50)),
                (
                    "pipeline_run_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("request_tokens", models.IntegerField(default=0)),
                ("response_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("request_count", models.IntegerField(default=1)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_usage_user_id_71a7cc_idx",
                    ),
                    models.Index(
                        fields=["agent_name", "created_at"],
                        name="ai_usage_agent_n_9d5041_idx",
                    ),
                ],
            },
            bases=(job_hunting.models.base.GetMixin, models.Model),
        ),
    ]
