# Generated by Django 6.0.3 on 2026-04-14 16:09

import django.db.models.deletion
import job_hunting.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0037_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("logged_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "scrape",
                    models.ForeignKey(
                        db_column="scrape_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_statuses",
                        to="job_hunting.scrape",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_column="status_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrape_statuses",
                        to="job_hunting.status",
                    ),
                ),
            ],
            options={
                "db_table": "scrape_status",
            },
            bases=(job_hunting.models.base.GetMixin, models.Model),
        ),
    ]
