# Generated by Django 6.0.3 on 2026-04-14 16:09

from django.db import migrations


SCRAPE_STATUSES = [
    "hold",
    "pending",
    "running",
    "authenticating",
    "login_failed",
    "scraping",
    "extracting",
    "completed",
    "failed",
]


def seed_statuses(apps, schema_editor):
    Status = apps.get_model("job_hunting", "Status")
    for label in SCRAPE_STATUSES:
        Status.objects.get_or_create(
            status=label,
            status_type="scrape",
        )


def remove_statuses(apps, schema_editor):
    Status = apps.get_model("job_hunting", "Status")
    Status.objects.filter(status__in=SCRAPE_STATUSES, status_type="scrape").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0038_scrapestatus"),
    ]

    operations = [
        migrations.RunPython(seed_statuses, remove_statuses),
    ]
