# Generated by Django 5.2.12 on 2026-04-14 19:18

import django.db.models.deletion
import job_hunting.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0039_seed_scrape_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('requires_auth', models.BooleanField(default=False)),
                ('avg_content_length', models.IntegerField(blank=True, null=True)),
                ('success_rate', models.FloatField(default=0.0)),
                ('css_selectors', models.JSONField(blank=True, null=True)),
                ('extraction_hints', models.TextField(blank=True, default='')),
                ('page_structure', models.TextField(blank=True, default='')),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('scrape_count', models.IntegerField(default=0)),
                ('preferred_tier', models.CharField(choices=[('auto', 'Auto'), ('0', 'Tier 0 — Deterministic'), ('1', 'Tier 1 — Mini + Hints'), ('2', 'Tier 2 — Haiku'), ('3', 'Tier 3 — Sonnet')], default='auto', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scrape_profile',
            },
            bases=(job_hunting.models.base.GetMixin, models.Model),
        ),
    ]
