# Generated by Django 5.2.12 on 2026-04-15 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0040_scrape_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('job_post', 'resume', 'user'), name='unique_score_per_job_resume_user'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('resume__isnull', True)), fields=('job_post', 'user'), name='unique_score_per_job_user_career_data'),
        ),
    ]
