# Generated by Django 5.2.12 on 2026-04-16 01:31

from django.db import migrations


def dedupe_companies(apps, schema_editor):
    """Merge duplicate Company rows before adding unique constraint.

    For each duplicated name, keep the row with the lowest id and
    re-point all FK references from the duplicates to the keeper,
    then delete the duplicates.
    """
    Company = apps.get_model("job_hunting", "Company")
    JobPost = apps.get_model("job_hunting", "JobPost")
    JobApplication = apps.get_model("job_hunting", "JobApplication")

    from django.db.models import Count, Min

    dupes = (
        Company.objects.values("name")
        .annotate(cnt=Count("id"), min_id=Min("id"))
        .filter(cnt__gt=1)
    )
    for entry in dupes:
        keeper_id = entry["min_id"]
        extras = Company.objects.filter(name=entry["name"]).exclude(id=keeper_id)
        extra_ids = list(extras.values_list("id", flat=True))

        # Re-point FKs
        JobPost.objects.filter(company_id__in=extra_ids).update(company_id=keeper_id)
        JobApplication.objects.filter(company_id__in=extra_ids).update(company_id=keeper_id)

        extras.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0041_unique_score_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RunPython(dedupe_companies, migrations.RunPython.noop),
    ]
