# Generated by Django 5.2.12 on 2026-04-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0043_company_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
