# Generated by Django 5.2.12 on 2026-04-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0046_backfill_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeprofile',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapeprofile',
            name='tier0_miss_count',
            field=models.IntegerField(default=0),
        ),
    ]
