# Generated by Django 5.2.12 on 2026-04-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0048_profile_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='source',
            field=models.CharField(default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='scrape',
            name='source',
            field=models.CharField(default='manual', max_length=32),
        ),
    ]
