# Generated by Django 5.2.12 on 2026-04-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0049_jobpost_source_scrape_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="auto_score",
            field=models.BooleanField(default=False),
        ),
    ]
