# Generated by Django 5.2.12 on 2026-04-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0050_profile_auto_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="apply_url",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="apply_url_resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="apply_url_status",
            field=models.CharField(default="unknown", max_length=16),
        ),
        migrations.AddField(
            model_name="scrape",
            name="apply_url",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="scrape",
            name="apply_url_status",
            field=models.CharField(default="unknown", max_length=16),
        ),
    ]
