# Generated by Django 5.2.12 on 2026-04-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_hunting",
            "0051_jobpost_apply_url_jobpost_apply_url_resolved_at_and_more",
        ),
    ]

    operations = [
        # Backfill NULL posted_date with created_at so existing rows surface
        # in list views that sort by posted_date. From-now-on the JobPost
        # save() override covers new inserts.
        migrations.RunSQL(
            sql="UPDATE job_post SET posted_date = created_at::date "
                "WHERE posted_date IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
