# Generated by Django 5.2.12 on 2026-04-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0052_backfill_posted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapestatus",
            name="graph_node",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="scrapestatus",
            name="graph_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
