# Generated by Django 5.2.12 on 2026-04-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0063_scrape_source_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPostDiscovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discoveries",
                        to="job_hunting.jobpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_post_discoveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job_post_discovery",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="job_post_di_user_id_beabef_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_post", "user"),
                        name="job_post_discovery_unique_user_post",
                    )
                ],
            },
        ),
    ]
