# Generated by Django 5.2.12 on 2026-05-05 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0067_recanonicalize_job_post_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPostOverwriteDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_source",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("new_source", models.CharField(blank=True, default="", max_length=32)),
                ("changed_fields", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "job_post_overwrite_decision",
            },
        ),
        migrations.RenameIndex(
            model_name="jobpostdescriptiondecision",
            new_name="job_post_de_job_pos_405d8d_idx",
            old_name="jp_desc_dec_job_post_created_idx",
        ),
        migrations.AlterField(
            model_name="jobpostdescriptiondecision",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="jobpostoverwritedecision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_overwrite_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jobpostoverwritedecision",
            name="job_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overwrite_decisions",
                to="job_hunting.jobpost",
            ),
        ),
        migrations.AddField(
            model_name="jobpostoverwritedecision",
            name="triggering_scrape",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overwrite_decisions",
                to="job_hunting.scrape",
            ),
        ),
        migrations.AddIndex(
            model_name="jobpostoverwritedecision",
            index=models.Index(
                fields=["job_post", "-created_at"],
                name="job_post_ov_job_pos_cc73c0_idx",
            ),
        ),
    ]
