# Generated by Django 5.2.12 on 2026-05-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0068_jobpostoverwritedecision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="profession",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
