# Generated by Django 5.2.12 on 2026-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0069_add_resume_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="section_order",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
