# Generated by Django 5.2.12 on 2026-05-08 21:01

from django.db import migrations, models


def backfill_complete_from_thin_description(apps, schema_editor):
    """One-time use of the soon-to-be-deleted word-count heuristic to
    seed `complete`. Rows whose description is empty or has fewer than
    60 whitespace tokens land complete=False — the same threshold that
    `_is_thin_description` used. After this migration the heuristic
    goes away and `complete` is the only signal."""
    JobPost = apps.get_model("job_hunting", "JobPost")
    STUB_MIN_WORDS = 60
    # Rows default to True; we only need to flip thin ones.
    for post in JobPost.objects.all().only("id", "description").iterator():
        desc = (post.description or "").strip()
        if not desc or len(desc.split()) < STUB_MIN_WORDS:
            JobPost.objects.filter(pk=post.pk).update(complete=False)


def noop_reverse(apps, schema_editor):
    """Reversal is a no-op — the column drop in AddField's reverse
    handles state restoration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0070_add_resume_section_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="complete",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(
            backfill_complete_from_thin_description,
            reverse_code=noop_reverse,
        ),
    ]
