# Generated by Django 5.2.12 on 2026-05-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0071_add_job_post_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrape",
            name="skip_extract",
            field=models.BooleanField(default=False),
        ),
    ]
