# Generated by Django 5.2.12 on 2026-05-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0073_scrape_detected_posting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='apply_url_from_hint',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='scrape',
            name='referrer_url',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
