# Generated by Django 5.2.12 on 2026-05-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunting', '0074_scrape_hint_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeprofile',
            name='extension_selectors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
