# Generated by Django 5.2.12 on 2026-05-27 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0079_strip_url_trailing_junk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("mark", "mark"),
                            ("unlink", "unlink"),
                            ("promote", "promote"),
                            ("historical", "historical"),
                        ],
                        max_length=16,
                    ),
                ),
                ("set_at", models.DateTimeField(auto_now_add=True)),
                ("signal_state", models.JSONField(blank=True, default=dict)),
                (
                    "from_jp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_annotations",
                        to="job_hunting.jobpost",
                    ),
                ),
                (
                    "previous_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="job_hunting.jobpost",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicate_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_jp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="job_hunting.jobpost",
                    ),
                ),
            ],
            options={
                "db_table": "duplicate_annotation",
                "indexes": [
                    models.Index(
                        fields=["from_jp", "-set_at"],
                        name="duplicate_a_from_jp_f4bfe9_idx",
                    ),
                    models.Index(
                        fields=["action", "-set_at"],
                        name="duplicate_a_action_e404f7_idx",
                    ),
                ],
            },
        ),
    ]
