# Generated by Django 5.2.12 on 2026-05-27 20:05

import job_hunting.models.job_post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0082_recompute_canonical_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="audience",
            field=models.JSONField(
                blank=True, default=job_hunting.models.job_post._default_audience_public
            ),
        ),
    ]
