# Generated by Django 5.2.12 on 2026-05-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0084_jobpost_source_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrape",
            name="claimed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="scrape",
            name="claimed_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
