"""CC-77 #79 — Score integer PK -> 10-char NanoID PK (true PK swap).

Score is a **leaf**: no foreign key anywhere references ``score(id)``, so
this is the simplest shape of the swap proven in
``0114_skill_nanoid_pk_swap`` — just the parent PK is repointed, with no
dependent FK columns to rebuild.

Score's two composite UNIQUE constraints (``unique_score_per_job_resume_user``
and the partial ``unique_score_per_job_user_career_data``) ride on
``job_post_id`` / ``resume_id`` / ``user_id`` — NOT on ``score.id`` — so the
PK swap leaves them untouched.

DB surgery is hand-written ``RunSQL`` (a PK-type change is not cleanly
auto-generated); Django's migration *state* is kept in sync with a single
``AlterField`` on ``score.id`` via ``SeparateDatabaseAndState``.

## Reverse path (down migration)

Reversing a destructive PK swap cannot restore the original integer ids.
The reverse re-mints a FRESH sequential integer PK (deterministic
``row_number`` order) — a structurally-valid integer-PK schema, NOT a
value-preserving round-trip.
"""

from __future__ import annotations

import logging

import job_hunting.models.nanoid_pk
from django.db import migrations, models

logger = logging.getLogger(__name__)


def backfill_nanoids(apps, schema_editor):
    """Mint a unique NanoID for every ``score`` row."""
    from job_hunting.models.nanoid_pk import generate_nanoid

    with schema_editor.connection.cursor() as cur:
        cur.execute("SELECT id FROM score ORDER BY id")
        score_ids = [row[0] for row in cur.fetchall()]

        used: set[str] = set()
        for old_id in score_ids:
            nid = generate_nanoid()
            while nid in used:  # astronomically rare; keep it deterministic
                nid = generate_nanoid()
            used.add(nid)
            cur.execute(
                "UPDATE score SET new_id = %s WHERE id = %s", [nid, old_id]
            )

    logger.info("0116 nanoid backfill: minted %s score ids.", len(score_ids))


ADD_STAGING_COLUMNS = """
ALTER TABLE score ADD COLUMN new_id varchar(10);
"""

DROP_STAGING_COLUMNS = """
ALTER TABLE score DROP COLUMN IF EXISTS new_id;
"""

SWAP_FORWARD = """
-- 1. Staging PK is fully backfilled: enforce NOT NULL before promotion.
ALTER TABLE score ALTER COLUMN new_id SET NOT NULL;

-- 2. Promote score's PK from the int id to the NanoID staging column.
DO $$
DECLARE cname text;
BEGIN
    SELECT conname INTO cname FROM pg_constraint
     WHERE conrelid = 'score'::regclass AND contype = 'p';
    EXECUTE format('ALTER TABLE score DROP CONSTRAINT %I', cname);
END $$;
ALTER TABLE score DROP COLUMN id;
ALTER TABLE score RENAME COLUMN new_id TO id;
ALTER TABLE score ADD CONSTRAINT score_pkey PRIMARY KEY (id);
"""

SWAP_REVERSE = """
-- Reverse a destructive PK swap: NanoID PK -> a FRESH integer PK.
ALTER TABLE score ADD COLUMN old_int_id bigint;
WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id) AS rn FROM score
)
UPDATE score s SET old_int_id = n.rn FROM numbered n WHERE s.id = n.id;

DO $$
DECLARE cname text;
BEGIN
    SELECT conname INTO cname FROM pg_constraint
     WHERE conrelid = 'score'::regclass AND contype = 'p';
    EXECUTE format('ALTER TABLE score DROP CONSTRAINT %I', cname);
END $$;
ALTER TABLE score DROP COLUMN id;
ALTER TABLE score RENAME COLUMN old_int_id TO id;
ALTER TABLE score ALTER COLUMN id SET NOT NULL;
ALTER TABLE score ADD CONSTRAINT score_pkey PRIMARY KEY (id);
ALTER TABLE score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('score', 'id'),
              (SELECT COALESCE(max(id), 1) FROM score));
"""


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0115_jobpost_nanoid_pk_swap"),
    ]

    operations = [
        migrations.RunSQL(
            sql=ADD_STAGING_COLUMNS,
            reverse_sql=DROP_STAGING_COLUMNS,
        ),
        migrations.RunPython(backfill_nanoids, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=SWAP_FORWARD, reverse_sql=SWAP_REVERSE),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="score",
                    name="id",
                    field=models.CharField(
                        default=job_hunting.models.nanoid_pk.generate_nanoid,
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
