"""CC-77 #79 — ScrapeProfile integer PK -> 10-char NanoID PK (true PK swap).

ScrapeProfile is a **leaf**: no foreign key references ``scrape_profile(id)``
(Scrape associates by hostname string, not an FK). So this is the simplest
shape of the swap proven in ``0114_skill_nanoid_pk_swap`` — only the parent
PK is repointed. The single-column UNIQUE on ``hostname`` does not touch
``id`` and is left intact.

Mechanism + reverse semantics: see ``0116_score_nanoid_pk_swap``.
"""

from __future__ import annotations

import logging

import job_hunting.models.nanoid_pk
from django.db import migrations, models

logger = logging.getLogger(__name__)


def backfill_nanoids(apps, schema_editor):
    """Mint a unique NanoID for every ``scrape_profile`` row."""
    from job_hunting.models.nanoid_pk import generate_nanoid

    with schema_editor.connection.cursor() as cur:
        cur.execute("SELECT id FROM scrape_profile ORDER BY id")
        ids = [row[0] for row in cur.fetchall()]

        used: set[str] = set()
        for old_id in ids:
            nid = generate_nanoid()
            while nid in used:  # astronomically rare; keep it deterministic
                nid = generate_nanoid()
            used.add(nid)
            cur.execute(
                "UPDATE scrape_profile SET new_id = %s WHERE id = %s",
                [nid, old_id],
            )

    logger.info("0117 nanoid backfill: minted %s scrape_profile ids.", len(ids))


ADD_STAGING_COLUMNS = """
ALTER TABLE scrape_profile ADD COLUMN new_id varchar(10);
"""

DROP_STAGING_COLUMNS = """
ALTER TABLE scrape_profile DROP COLUMN IF EXISTS new_id;
"""

SWAP_FORWARD = """
-- 1. Staging PK is fully backfilled: enforce NOT NULL before promotion.
ALTER TABLE scrape_profile ALTER COLUMN new_id SET NOT NULL;

-- 2. Promote scrape_profile's PK from the int id to the NanoID column.
DO $$
DECLARE cname text;
BEGIN
    SELECT conname INTO cname FROM pg_constraint
     WHERE conrelid = 'scrape_profile'::regclass AND contype = 'p';
    EXECUTE format('ALTER TABLE scrape_profile DROP CONSTRAINT %I', cname);
END $$;
ALTER TABLE scrape_profile DROP COLUMN id;
ALTER TABLE scrape_profile RENAME COLUMN new_id TO id;
ALTER TABLE scrape_profile ADD CONSTRAINT scrape_profile_pkey PRIMARY KEY (id);
"""

SWAP_REVERSE = """
-- Reverse a destructive PK swap: NanoID PK -> a FRESH integer PK.
ALTER TABLE scrape_profile ADD COLUMN old_int_id bigint;
WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id) AS rn FROM scrape_profile
)
UPDATE scrape_profile s SET old_int_id = n.rn FROM numbered n WHERE s.id = n.id;

DO $$
DECLARE cname text;
BEGIN
    SELECT conname INTO cname FROM pg_constraint
     WHERE conrelid = 'scrape_profile'::regclass AND contype = 'p';
    EXECUTE format('ALTER TABLE scrape_profile DROP CONSTRAINT %I', cname);
END $$;
ALTER TABLE scrape_profile DROP COLUMN id;
ALTER TABLE scrape_profile RENAME COLUMN old_int_id TO id;
ALTER TABLE scrape_profile ALTER COLUMN id SET NOT NULL;
ALTER TABLE scrape_profile ADD CONSTRAINT scrape_profile_pkey PRIMARY KEY (id);
ALTER TABLE scrape_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('scrape_profile', 'id'),
              (SELECT COALESCE(max(id), 1) FROM scrape_profile));
"""


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0116_score_nanoid_pk_swap"),
    ]

    operations = [
        migrations.RunSQL(
            sql=ADD_STAGING_COLUMNS,
            reverse_sql=DROP_STAGING_COLUMNS,
        ),
        migrations.RunPython(backfill_nanoids, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=SWAP_FORWARD, reverse_sql=SWAP_REVERSE),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="scrapeprofile",
                    name="id",
                    field=models.CharField(
                        default=job_hunting.models.nanoid_pk.generate_nanoid,
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
