"""CC-77 #79 — Answer integer PK -> 10-char NanoID PK (true PK swap).

Answer is a **leaf**: no foreign key references ``answer(id)``. So this is
the simplest shape of the swap proven in ``0114_skill_nanoid_pk_swap`` —
only the parent PK is repointed. Answer's own ``question_id`` FK is repointed
when Question swaps (``0120``), not here.

Mechanism + reverse semantics: see ``0116_score_nanoid_pk_swap``.
"""

from __future__ import annotations

import logging

import job_hunting.models.nanoid_pk
from django.db import migrations, models

logger = logging.getLogger(__name__)


def backfill_nanoids(apps, schema_editor):
    """Mint a unique NanoID for every ``answer`` row."""
    from job_hunting.models.nanoid_pk import generate_nanoid

    with schema_editor.connection.cursor() as cur:
        cur.execute("SELECT id FROM answer ORDER BY id")
        ids = [row[0] for row in cur.fetchall()]

        used: set[str] = set()
        for old_id in ids:
            nid = generate_nanoid()
            while nid in used:  # astronomically rare; keep it deterministic
                nid = generate_nanoid()
            used.add(nid)
            cur.execute(
                "UPDATE answer SET new_id = %s WHERE id = %s", [nid, old_id]
            )

    logger.info("0118 nanoid backfill: minted %s answer ids.", len(ids))


ADD_STAGING_COLUMNS = """
ALTER TABLE answer ADD COLUMN new_id varchar(10);
"""

DROP_STAGING_COLUMNS = """
ALTER TABLE answer DROP COLUMN IF EXISTS new_id;
"""

SWAP_FORWARD = """
-- 1. Staging PK is fully backfilled: enforce NOT NULL before promotion.
ALTER TABLE answer ALTER COLUMN new_id SET NOT NULL;

-- 2. Promote answer's PK from the int id to the NanoID staging column.
DO $$
DECLARE cname text;
BEGIN
    SELECT conname INTO cname FROM pg_constraint
     WHERE conrelid = 'answer'::regclass AND contype = 'p';
    EXECUTE format('ALTER TABLE answer DROP CONSTRAINT %I', cname);
END $$;
ALTER TABLE answer DROP COLUMN id;
ALTER TABLE answer RENAME COLUMN new_id TO id;
ALTER TABLE answer ADD CONSTRAINT answer_pkey PRIMARY KEY (id);
"""

SWAP_REVERSE = """
-- Reverse a destructive PK swap: NanoID PK -> a FRESH integer PK.
ALTER TABLE answer ADD COLUMN old_int_id bigint;
WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id) AS rn FROM answer
)
UPDATE answer a SET old_int_id = n.rn FROM numbered n WHERE a.id = n.id;

DO $$
DECLARE cname text;
BEGIN
    SELECT conname INTO cname FROM pg_constraint
     WHERE conrelid = 'answer'::regclass AND contype = 'p';
    EXECUTE format('ALTER TABLE answer DROP CONSTRAINT %I', cname);
END $$;
ALTER TABLE answer DROP COLUMN id;
ALTER TABLE answer RENAME COLUMN old_int_id TO id;
ALTER TABLE answer ALTER COLUMN id SET NOT NULL;
ALTER TABLE answer ADD CONSTRAINT answer_pkey PRIMARY KEY (id);
ALTER TABLE answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('answer', 'id'),
              (SELECT COALESCE(max(id), 1) FROM answer));
"""


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0117_scrapeprofile_nanoid_pk_swap"),
    ]

    operations = [
        migrations.RunSQL(
            sql=ADD_STAGING_COLUMNS,
            reverse_sql=DROP_STAGING_COLUMNS,
        ),
        migrations.RunPython(backfill_nanoids, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=SWAP_FORWARD, reverse_sql=SWAP_REVERSE),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="answer",
                    name="id",
                    field=models.CharField(
                        default=job_hunting.models.nanoid_pk.generate_nanoid,
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
