# Generated by Django 5.2.12 on 2026-07-21 16:44
#
# CC-214 — the self-host / local async Job queue. Doug-approved new table.
# makemigrations also wanted to fold in a batch of unrelated index renames +
# id AlterFields (pre-existing model-state drift already on main, from the
# federation/companyalias work) — those are deliberately omitted here so this
# migration carries ONLY the Job table + its claim index.

import job_hunting.models.base
import job_hunting.models.nanoid_pk
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0134_fold_match_into_jobapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=job_hunting.models.nanoid_pk.generate_nanoid,
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("claimed_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "run_after",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "job",
            },
            bases=(job_hunting.models.base.GetMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                models.OrderBy(models.F("created_at"), nulls_first=True),
                models.F("id"),
                models.F("run_after"),
                condition=models.Q(("claimed_at__isnull", True), ("status", "pending")),
                name="job_claim_queue_idx",
            ),
        ),
    ]
