"""CC-221 — capture the accumulated model-state drift in one migration.

``makemigrations`` on ``main`` had been generating this diff for months, so
every migration author since had to hand-strip it out of their own file
(CC-204's 0136 and CC-213 both paid that tax). This migration lands it once so
``makemigrations --check`` is clean and stays that way — the invariant is
pinned by ``tests/test_cc221_migration_drift.py``.

The drift is two unrelated things:

1. **Index renames.** ``Meta.indexes`` on ``CompanyAlias``,
   ``FederationActivity`` and ``FederationFollower`` declare their indexes
   without an explicit ``name=``, so Django derives the usual hashed name,
   while migrations 0088/0098/0108 created them under hand-written short
   names. Autogenerated ``RenameIndex`` operations reconcile that.

2. **``AutoField`` → ``BigAutoField`` on the federation ``id`` columns.**
   ``JobHuntingConfig.default_auto_field`` is ``BigAutoField``, but 0087, 0088
   and 0098 were hand-written and spelled ``models.AutoField`` outright,
   overriding it. The four federation tables really do still have ``integer``
   ids, so these ``AlterField``s emit an actual ``ALTER COLUMN ... TYPE
   bigint`` rather than a state-only fixup. That is a widening — it rewrites
   the table under an ACCESS EXCLUSIVE lock but cannot lose data, and the
   federation tables are small.

   (``federationfollower.company`` is a ``help_text``-only ``AlterField`` —
   pure state, no DDL.)

**Why two of the renames are not plain ``RenameIndex``.** 0124 (the Company
nanoid PK swap) rewrote every ``company_id`` column in raw SQL and recreated
their indexes under its own convention. 0124 is unconditional and sits in the
linear chain, so on any database that has run it ``company_ali_company_idx``
and ``fed_fwr_company_idx`` are gone, replaced by
``company_alias_company_id_idx`` and ``federation_followers_company_id_idx``.
Migration *state* never learned that, so the autogenerated ``RenameIndex``
for those two renames a relation that isn't there and dies with
``ProgrammingError: relation "company_ali_company_idx" does not exist``
(reproduced against a fresh migrate-from-zero database). They are wrapped in
``SeparateDatabaseAndState`` instead: state takes the ``RenameIndex`` it
expects, while the database renames the index it actually has. That converges
state and schema rather than papering over the gap.

**What this does not fix.** The nanoid PK swaps (0119–0124) rebuilt roughly
forty-five FK columns in raw SQL and gave each one a single hand-named
``<table>_<column>_idx``, so the Django-hashed ``<table>_<column>_<hash>``
index and its ``varchar_pattern_ops`` ``_like`` sibling are absent almost
everywhere — state believes in names the database has never had. That is a
much larger repair than this migration, and it is untouched here. The one
consequence worth naming: after the two renames above,
``company_alias.company_id`` and ``federation_followers.company_id`` are down
to a *single* index apiece and it now carries a ``Meta.indexes`` name, so
dropping that index by name would leave the FK with no index at all.
``test_indexed_columns_have_a_backing_index`` fails the build if that ever
happens.
"""

import django.db.models.deletion
from django.db import migrations, models

# 0124 left these two indexes under its own raw-SQL names. Renaming them with
# a bare ``ALTER INDEX IF EXISTS`` would be worse than useless: if the source
# is missing the statement no-ops, the migration reports OK, and state records
# a rename that never happened — which is exactly the state/schema divergence
# this migration exists to close, re-armed on the one path (prod) where the
# test gate never runs. So: rename when the source is there, accept the target
# already being there (a re-run, or a database built after this migration),
# and raise when neither is.


def _rename_index(source, target):
    # No format placeholders in the RAISE message on purpose: ``RunSQL`` hands
    # the statement to the cursor with ``params=None``, so a ``%`` would reach
    # PL/pgSQL unchanged and mean something there.
    return (
        "DO $$\n"
        "BEGIN\n"
        f"    IF to_regclass('{source}') IS NOT NULL THEN\n"
        f"        ALTER INDEX {source} RENAME TO {target};\n"
        f"    ELSIF to_regclass('{target}') IS NULL THEN\n"
        f"        RAISE EXCEPTION 'CC-221 (0138): neither {source} nor "
        f"{target} exists; migration state and this schema have diverged "
        "further than 0138 can repair.';\n"
        "    END IF;\n"
        "END $$;"
    )


# Each is wrapped in a list so ``RunSQL`` hands it to the cursor whole rather
# than running it through ``prepare_sql_script``'s statement splitter, which
# has no business inside a dollar-quoted block.
RENAME_COMPANY_ALIAS_IDX = [
    _rename_index("company_alias_company_id_idx", "company_ali_company_3cd3ce_idx")
]
UNRENAME_COMPANY_ALIAS_IDX = [
    _rename_index("company_ali_company_3cd3ce_idx", "company_alias_company_id_idx")
]
RENAME_FED_FOLLOWER_IDX = [
    _rename_index(
        "federation_followers_company_id_idx", "federation__company_1916d2_idx"
    )
]
UNRENAME_FED_FOLLOWER_IDX = [
    _rename_index(
        "federation__company_1916d2_idx", "federation_followers_company_id_idx"
    )
]


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunting", "0137_summary_job_post_nanoid_fk"),
    ]

    operations = [
        # --- index renames the database can take at face value ---
        migrations.RenameIndex(
            model_name="federationactivity",
            new_name="federation__activit_917ffd_idx",
            old_name="fed_act_type_ctime_idx",
        ),
        migrations.RenameIndex(
            model_name="federationactivity",
            new_name="federation__actor_u_97b993_idx",
            old_name="fed_act_actor_uri_idx",
        ),
        migrations.RenameIndex(
            model_name="federationfollower",
            new_name="federation__instanc_e8317a_idx",
            old_name="fed_fwr_inst_host_idx",
        ),
        migrations.RenameIndex(
            model_name="federationfollower",
            new_name="federation__unfollo_7e5e32_idx",
            old_name="fed_fwr_unfwd_at_idx",
        ),
        # --- the two 0124 rewrote out from under migration state ---
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="companyalias",
                    new_name="company_ali_company_3cd3ce_idx",
                    old_name="company_ali_company_idx",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=RENAME_COMPANY_ALIAS_IDX,
                    reverse_sql=UNRENAME_COMPANY_ALIAS_IDX,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="federationfollower",
                    new_name="federation__company_1916d2_idx",
                    old_name="fed_fwr_company_idx",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=RENAME_FED_FOLLOWER_IDX,
                    reverse_sql=UNRENAME_FED_FOLLOWER_IDX,
                ),
            ],
        ),
        # --- AutoField -> BigAutoField on the federation tables ---
        migrations.AlterField(
            model_name="actor",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="companyalias",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="federationactivity",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="federationfollower",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Phase 6b — Company being followed (Organization-actor followee). NULL for pure Person-actor follows. May co-exist with ``local_user`` when a local user subscribes to a Company (the discovery channel for inbound JP ingest).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="federation_followers",
                to="job_hunting.company",
            ),
        ),
        migrations.AlterField(
            model_name="federationfollower",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
